name = "notification-system"
main = "worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "NOTIFICATIONS"
id = "625309fe0abc47baa1da1084a7bd822f"
preview_id = "10f4c8bf90a140c9ba627cdd759c58a3"

[observability]
enabled = true

[vars]
GITHUB_CLIENT_ID = "Ov23liayFBY4kRqe8tC2"
