name = "notify"
main = "worker.js"
workers_dev = true
preview_urls = true
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "NOTIFICATIONS"
id = "b2f2c549538a454ca82e1bc30008e55d"
# preview_id = "你的Preview_ID"

[observability]
enabled = true

[vars]
# GITHUB_CLIENT_ID = "你的GitHub OAuth Client ID"
