name = "notification-system"
main = "worker.js"
compatibility_date = "2026-6-23"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "NOTIFICATIONS"
id = "xxx"
preview_id = "xxx"

[observability]
enabled = true
